apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-docker
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Retain
  nfs: 
    path: /nfs/Docker
    server: 192.168.1.201
    readOnly: false
